export const SET_ROUTE_PROFILE = 'SET_ROUTE_PROFILE';
export const RESET_ROUTE_PROFILE = 'RESET_ROUTE_PROFILE';

export const LOGIN_REQUEST_STARTS = 'LOGIN_REQUEST_STARTS'
export const LOGIN_REQUEST_ENDS = 'LOGIN_REQUEST_ENDS'
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT'
export const LOGIN_PERFORM_LOGIN = 'LOGIN_PERFORM_LOGIN'
export const LOGIN_RESET_STATE = 'LOGIN_RESET_STATE'

