export const SET_ROUTE_PROFILE = 'SET_ROUTE_PROFILE';
export const RESET_ROUTE_PROFILE = 'RESET_ROUTE_PROFILE';

export const LOGIN_REQUEST_STARTS = 'LOGIN_REQUEST_STARTS'
export const LOGIN_REQUEST_ENDS = 'LOGIN_REQUEST_ENDS'
export const LOGIN_REQUEST_FAILED = 'LOGIN_REQUEST_FAILED'
export const LOGIN_REQUEST_SUCCESS = 'LOGIN_REQUEST_SUCCESS'
export const LOGIN_LOGOUT = 'LOGIN_LOGOUT'
export const LOGIN_PERFORM_LOGIN = 'LOGIN_PERFORM_LOGIN'
export const LOGIN_RESET_STATE = 'LOGIN_RESET_STATE'

// Welcome

export const WELCOME_REQUEST_STARTS = 'WELCOME_REQUEST_STARTS';
export const WELCOME_REQUEST_ENDS = 'WELCOME_REQUEST_ENDS';
export const WELCOME_REQUEST_FAILED = 'WELCOME_REQUEST_FAILED';
export const WELCOME_REQUEST_SUCCESS = 'WELCOME_REQUEST_SUCCESS';
export const WELCOME_RESET_STATE = 'WELCOME_RESET_STATE';
export const WELCOME_PERFORME_FETCH='WELCOME_PERFORME_FETCH'

// PRODUCTS

export const PRODUCTS_REQUEST_STARTS='PRODUCTS_REQUEST_STARTS';
export const PRODUCTS_REQUEST_ENDS='PRODUCTS_REQUEST_ENDS';
export const PRODUCTS_REQUEST_FAILED='PRODUCTS_REQUEST_FAILED,';
export const PRODUCTS_REQUEST_SUCCESS='PRODUCTS_REQUEST_SUCCESS,';
export const PRODUCTS_PERFORME_FETCH='PRODUCTS_PERFORME_FETCH,';
export const PRODUCTS_RESET_STATE='PRODUCTS_RESET_STATE';

